#!/usr/bin/env python3
"""
Memory Statistics Visualization Script
Plots memory usage statistics over time from CSV files generated by record_memory_stats.sh
"""

import pandas as pd
import matplotlib
matplotlib.use('Agg')  # 使用非交互式后端
import matplotlib.pyplot as plt
import numpy as np
import argparse
import os
import sys
import glob

def find_csv_file(program_name, directory='memory_stats_results'):
    """
    Find CSV file based on program name
    
    Args:
        program_name: Name of the program (e.g., 'miniz', 'genann')
        directory: Directory to search in
    
    Returns:
        Path to the CSV file or None if not found
    """
    # Try different patterns
    patterns = [
        f"{directory}/{program_name}_memory_stats_results.csv",
        f"{directory}/{program_name}.ke_memory_stats_results.csv",
        f"{directory}/*{program_name}*_memory_stats_results.csv"
    ]
    
    for pattern in patterns:
        files = glob.glob(pattern)
        if files:
            return files[0]
    
    return None

def plot_memory_usage(csv_file):
    """
    Plot memory usage over time from CSV file with step-like behavior
    
    Args:
        csv_file: Path to the CSV file containing memory statistics
    """
    # Check if file exists
    if not os.path.exists(csv_file):
        print(f"Error: File {csv_file} does not exist")
        return
    
    # Read CSV file
    try:
        df = pd.read_csv(csv_file)
        print(f"Successfully loaded: {csv_file}")
        print(f"Data points: {len(df)}")
    except Exception as e:
        print(f"Error reading CSV file: {e}")
        return
    
    # Validate required columns
    required_columns = ['Memory_Utilization_Percent', 'Timestamp_Cycles', 'Heap_Used_Bytes', 'Total_Memory_Bytes']
    for col in required_columns:
        if col not in df.columns:
            print(f"Error: Required column '{col}' not found in CSV file")
            return
    
    # Extract data
    memory_utilization = df['Memory_Utilization_Percent'].values
    timestamps = df['Timestamp_Cycles'].values
    heap_used = df['Heap_Used_Bytes'].values
    total_memory = df['Total_Memory_Bytes'].values
    
    # Recalculate memory utilization for entries that show 0.0%
    recalculated_count = 0
    for i in range(len(memory_utilization)):
        if memory_utilization[i] == 0.0 and total_memory[i] > 0:
            # Recalculate using the formula: (Heap_Used_Bytes / Total_Memory_Bytes) * 100
            new_utilization = (heap_used[i] / total_memory[i]) * 100
            memory_utilization[i] = new_utilization
            recalculated_count += 1
    
    if recalculated_count > 0:
        print(f"Recalculated {recalculated_count} data points where Memory_Utilization_Percent was 0.0%")
    
    if len(timestamps) == 0:
        print("Error: No data found in CSV file")
        return
    
    # Calculate relative time in cycles (starting from 0)
    start_time = timestamps[0]
    relative_cycles = timestamps - start_time
    
    print(f"Time range: 0 to {relative_cycles[-1]:,} cycles")
    print(f"Memory range: {min(memory_utilization):.2f}% to {max(memory_utilization):.2f}%")
    
    # Create step-like data for flat lines between points
    # Each memory value should persist until the next measurement
    step_times = []
    step_memory = []
    
    # Add each data point with step behavior (start from first actual measurement)
    for i in range(len(relative_cycles)):
        # Add the point at the measurement time
        step_times.append(relative_cycles[i])
        step_memory.append(memory_utilization[i])
        
        # If not the last point, add a continuation point just before the next measurement
        if i < len(relative_cycles) - 1:
            step_times.append(relative_cycles[i+1] - 1)  # Just before next measurement
            step_memory.append(memory_utilization[i])    # Same memory value
    
    # Convert to numpy arrays
    step_times = np.array(step_times)
    step_memory = np.array(step_memory)
    
    # Create the plot
    plt.figure(figsize=(14, 8))
    
    # Plot the memory usage over time with step-like behavior (no markers)
    plt.plot(step_times, step_memory, 'b-', linewidth=2.5, alpha=0.8, label='Memory Usage')
    
    # Customize the plot
    plt.xlabel('Time (Cycles)', fontsize=14)
    plt.ylabel('Memory Utilization (%)', fontsize=14)
    plt.title(f'Memory Usage Over Time\n{os.path.basename(csv_file)}', fontsize=16, fontweight='bold')
    plt.grid(True, alpha=0.3, linestyle='--')
    
    # Set y-axis to start from 0 and add some padding
    plt.ylim(0, max(step_memory) * 1.1)
    
    # Set x-axis to start from 0 (time axis) but data line starts from first measurement
    # Add a small gap before first data point to make it clear the line starts there
    first_data_time = relative_cycles[0]
    plt.xlim(-first_data_time * 0.05, max(step_times) * 1.05)
    
    # Add a vertical dashed line at x=0 to show the start of measurement period
    plt.axvline(x=0, color='gray', linestyle=':', alpha=0.5, label='Program Start')
    
    # Add annotations for peak memory usage
    max_memory_idx = np.argmax(memory_utilization)
    max_memory = memory_utilization[max_memory_idx]
    max_time = relative_cycles[max_memory_idx]
    
    plt.annotate(f'Peak: {max_memory:.2f}%\nat {max_time:,} cycles', 
                xy=(max_time, max_memory), 
                xytext=(max_time + max(step_times)*0.15, max_memory + max(step_memory)*0.08),
                arrowprops=dict(arrowstyle='->', color='red', lw=2),
                fontsize=12, ha='left',
                bbox=dict(boxstyle='round,pad=0.3', facecolor='yellow', alpha=0.7))
    
    # Add statistics text box
    stats_text = f'Statistics:\n'
    stats_text += f'• Peak Memory: {max_memory:.2f}%\n'
    stats_text += f'• Min Memory: {min(memory_utilization):.2f}%\n'
    stats_text += f'• Average: {np.mean(memory_utilization):.2f}%\n'
    stats_text += f'• Duration: {max(relative_cycles):,} cycles\n'
    stats_text += f'• Measurements: {len(memory_utilization)}'
    
    plt.text(0.02, 0.98, stats_text, transform=plt.gca().transAxes, 
             verticalalignment='top', 
             bbox=dict(boxstyle='round,pad=0.5', facecolor='lightblue', alpha=0.8),
             fontsize=11, family='monospace')
    
    # Add legend
    plt.legend(fontsize=12)
    
    plt.tight_layout()
    
    # Save the plot
    output_file = csv_file.replace('.csv', '_plot.png')
    plt.savefig(output_file, dpi=300, bbox_inches='tight')
    print(f"Plot saved as: {output_file}")
    
    # Don't show plot in server environment
    # plt.show()

def plot_all_csv_files(directory):
    """
    Plot all CSV files in the given directory
    
    Args:
        directory: Directory containing CSV files
    """
    if not os.path.exists(directory):
        print(f"Error: Directory {directory} does not exist")
        return
    
    csv_files = [f for f in os.listdir(directory) if f.endswith('_memory_stats_results.csv')]
    
    if not csv_files:
        print(f"No memory stats CSV files found in {directory}")
        return
    
    print(f"Found {len(csv_files)} CSV files to plot:")
    for csv_file in csv_files:
        print(f"  - {csv_file}")
        full_path = os.path.join(directory, csv_file)
        plot_memory_usage(full_path)

def main():
    parser = argparse.ArgumentParser(description='Plot memory usage statistics from CSV files')
    parser.add_argument('--file', '-f', type=str, 
                        help='Program name (e.g., "miniz") or full path to CSV file')
    parser.add_argument('--directory', '-d', type=str, default='memory_stats_results',
                        help='Directory containing CSV files (default: memory_stats_results)')
    parser.add_argument('--all', '-a', action='store_true',
                        help='Plot all CSV files in the directory')
    
    args = parser.parse_args()
    
    if args.file:
        # Check if it's a full path or just a program name
        if args.file.endswith('.csv') and os.path.exists(args.file):
            # Full path provided
            plot_memory_usage(args.file)
        else:
            # Program name provided, try to find the CSV file
            csv_file = find_csv_file(args.file, args.directory)
            if csv_file:
                print(f"Found CSV file for '{args.file}': {csv_file}")
                plot_memory_usage(csv_file)
            else:
                print(f"Error: Could not find CSV file for program '{args.file}' in directory '{args.directory}'")
                print("Available files:")
                if os.path.exists(args.directory):
                    files = [f for f in os.listdir(args.directory) if f.endswith('_memory_stats_results.csv')]
                    for f in files:
                        print(f"  - {f}")
                else:
                    print(f"  Directory '{args.directory}' does not exist")
    elif args.all:
        # Plot all files in directory
        plot_all_csv_files(args.directory)
    else:
        # Default: plot all files
        plot_all_csv_files(args.directory)
    
if __name__ == "__main__":
    main()
